### ISSUE TITLE
Object Detection Network

### ISSUE THREAD

**Issue by p-akanksha** [MIT-TESSE/tesse-segmentation-ros#2]
Hi, 

I am using MIT-TESSE for an academic project. I was just wondering if there is a publically available object detection network for this simulator (just like this segmentation network). It'll be a great help if you can point me to it, if that is available. 

Thanks,
Akanksha Patel

**Comment by ZacRavichandran** [comment]
Hi @p-akanksha,

Unfortunately there is not. However, we do provide instance segmentation. So, if you need to extract bounding boxes, you could potentially get unique objects via instance label then correlate that to class via semantic segmentation. 

Best,
Zac

**Comment by p-akanksha** [comment]
Hi @ZacRavichandran,

Thanks for the response. That should work. So, there is a separate network for instance segmentation? Because the output of this one only seems to give semantic segmentation. (I mean, two chairs in a scene are assigned the same color). If you can point me to an example code where the instance segmented output is used, it'll be extremely helpful.  

Thanks, 
Akanksha Patel

**Comment by ZacRavichandran** [comment]
Hi @p-akanksha 

No, sorry for the confusion - instance segmentation ground truth labels are available, but there is not a readily available network for this. To read instance segmentation labels, you can extend the requested camera information [here](https://github.com/MIT-TESSE/tesse-segmentation-ros/blob/master/training/tesse_semantic_segmentation/data.py#L64-L67) to be 

```python
        cameras = [
            (Camera.RGB_LEFT, Compression.OFF, Channels.THREE),
            (Camera.SEGMENTATION, Compression.OFF, Channels.THREE),
            (Camera.INSTANCE_SEGMENTATION , Compression.OFF, Channels.THREE),
        ]
```
